# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae39a5d359885cd56b85e7dac0949f254cf5141fe18dddf61fd57b5ef9ba8dbdf0d8291cd09b4a6b4ff713cfdbe16137e7a6e4bbc5b81e6eaa8a6574297adc94

test:
  secret_key_base: aafe16e23da4ddd101087ae8705af03dbdb0aad5b52bd317ca570955535bbd94e73dc330f78e2166fd28f43f8b2f277044e5694dbbf71bca003faae9a0a9cd84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
